### ISSUE TITLE
About nestandart 2.0

### ISSUE THREAD

**Issue by hey-red** [henkmollema/CryptoHelper#17]
Is there any reason to use net standard 2.0? Yes, we are getting large API set, but lost compatible with all projects <2.0.
Ofcourse, we can still use old version without problem(and without security updates 😫) or upgrade app to new  target framework, but I'm really don't understand why use netstandart 2.0 for library project(if it really don't needs).

**Comment by henkmollema** [comment]
CryptoHelper depends on the ASP.NET Core Data Protection stack to provide its hashing functionality. CrypyoHelper version 3.0 uses [Microsoft.AspNetCore.Cryptography.KeyDerivation v2.0](https://www.nuget.org/packages/Microsoft.AspNetCore.Cryptography.KeyDerivation/2.0.0) which targets .NET Standard 2.0.

If you want to target a .NET Standard 1.x version, you should use v2.1.1 of CryptoHelper and pull in the latest patch 1.x.x patch release of the data protection package.

**Comment by hey-red** [comment]
Ok. Thanks for information 😌
