### ISSUE TITLE
Salting

### ISSUE THREAD

**Issue by mitiko** [henkmollema/CryptoHelper#20]
Salts are necessary to protect form rainbow dictionary attacks

**Comment by dpaquette** [comment]
The implementation uses a 128 bit salt:
https://github.com/henkmollema/CryptoHelper/blob/f00a074ed3a773f084aedc2fca03099744312ae8/src/CryptoHelper/Crypto.cs#L86

**Comment by henkmollema** [comment]
As David mentioned, a salt is indeed added to the password hash.
