### ISSUE TITLE
Migrate to .NETStandard

### ISSUE THREAD

**Issue by kevinchalet** [henkmollema/CryptoHelper#9]
CryptoHelper is currently targeting `dotnet5.4` which is being replaced by `netstandard1.3` everywhere, including the ASP.NET Core and aspnet-contrib projects. That would be great if CryptoHelper could be updated to use the new TFM (no hurries, of course, since we can use the `imports` section to make `dotnet5.4` compatible with `netstandard1.3`).

Pushing a new build would also fix the weird assembly version issues we're seeing with DNX. Here's more context: https://github.com/openiddict/openiddict-core/issues/76#issuecomment-201058572 (it's about IdentityModel, but CryptoHelper is similarly impacted)

https://github.com/henkmollema/CryptoHelper/blob/master/src/CryptoHelper/project.json#L29

Thanks!

/cc @henkmollema

**Comment by henkmollema** [comment]
Thanks for the heads up. I'll look into it asap. :+1:

**Comment by kevinchalet** [comment]
Closing, as this was fixed a while ago (https://github.com/henkmollema/CryptoHelper/commit/3074747b4ac9dc66020f71b0374bd7eec8a8b21f) :smile: 

Thanks :clap:
